TEXT_BASE = 0x48d00000

PLL400 ?= 733333333
RPSCLK ?=  25000000

NAS_VERSION ?= 810
FPGA ?= 0
FPGA_ARM_CLK ?= 25000000

PROBE_MEM_SIZE ?= 1
MEM_SIZE ?= 64	# Memory size in megabytes if probing is not enabled
MEM_ODT ?= 150

USE_SATA ?= 0
USE_SATA_ENV ?= 0
USE_FLASH ?= 1

LINUX_ROOT_RAIDED ?= 1

USE_EXTERNAL_UART ?= 0
INTERNAL_UART ?= 3

USE_LEON_TIME_COUNT ?= 1 # uses leon counted time to update system time on power-up

TEST_BRD ?= 0	# Only significant for OX800

MODEL ?= NSA210

PLATFORM_CPPFLAGS += -DLINUX_ROOT_RAIDED=$(LINUX_ROOT_RAIDED) -DMEM_ODT=$(MEM_ODT) -DPROBE_MEM_SIZE=$(PROBE_MEM_SIZE) -DNAS_VERSION=$(NAS_VERSION) -DFPGA=$(FPGA) -DFPGA_ARM_CLK=$(FPGA_ARM_CLK) -DINTERNAL_UART=$(INTERNAL_UART) -DUSE_EXTERNAL_UART=$(USE_EXTERNAL_UART) -DMEM_SIZE=$(MEM_SIZE) -DPLL400=$(PLL400) -DRPSCLK=$(RPSCLK) -DTEST_BRD=$(TEST_BRD) -DUSE_SATA=$(USE_SATA) -DUSE_SATA_ENV=$(USE_SATA_ENV) -DUSE_FLASH=$(USE_FLASH) -DUSE_LEON_TIME_COUNT=$(USE_LEON_TIME_COUNT) -D$(MODEL)
